USE sakila;

#Write SQL queries to perform the following tasks using the Sakila database:

#List the number of films per category.
select fc.category_id,COUNT(*) AS count_of_films
FROM film AS f
left join film_category AS fc
ON f.film_id = fc.film_id
Group by fc.category_id;

#Retrieve the store ID, city, and country for each store.
select * from store;
SELECT s.store_id, c.city, co.country
FROM store s
JOIN address a ON s.address_id = a.address_id
JOIN city c ON a.city_id = c.city_id
JOIN country co ON c.country_id = co.country_id;

#Calculate the total revenue generated by each store in dollars.
SELECT * from sakila.store;
Select * from payment;

SELECT s.store_id, SUM(p.amount) AS total_revenue
FROM payment p
JOIN rental r ON p.rental_id = r.rental_id
JOIN inventory i ON r.inventory_id = i.inventory_id
JOIN store s ON i.store_id = s.store_id
GROUP BY s.store_id;


#Determine the average running time of films for each category.


SELECT category.name, ROUND(AVG(film.length), 2) AS average_running_time
FROM category
JOIN film_category ON category.category_id = film_category.category_id
JOIN film ON film_category.film_id = film.film_id
GROUP BY category.name;
