USE sakila;

#Write SQL queries to perform the following tasks using the Sakila database:

#List the number of films per category.
select fc.category_id,COUNT(*) AS count_of_films
FROM film AS f
left join film_category AS fc
ON f.film_id = fc.film_id
Group by fc.category_id;

#Retrieve the store ID, city, and country for each store.
select * from store;
select s.store_id,c.city,ctry.country
from store AS s
left join address as a 
left join city as c on c.city_id=a.city_id
left join country as ctry on c.country_id=c.country_id
on s.address_id=a.address_id;

#Calculate the total revenue generated by each store in dollars.
SELECT * from sakila.store;
Select * from payment;

SELECT s.store_id, SUM(p.amount) AS total_revenue
FROM payment p
JOIN rental r ON p.rental_id = r.rental_id
JOIN inventory i ON r.inventory_id = i.inventory_id
JOIN store s ON i.store_id = s.store_id
GROUP BY s.store_id;


#Determine the average running time of films for each category.
select * from film_category;
select category_id, AVG(length) as avg_running_time
from film as f
left join film_category as fc
on f.film_id=fc.film_id
group by category_id ;


